### ISSUE TITLE
没写作业有更简单的api

### ISSUE THREAD

**Issue by awesomehhhhh** [cjyx9/FakeAnoah#1]
http://api2.anoah.com/jwt/homework/publish/getUndoNumForStudent?user_id=%s&class_id=%s&from_date=&to_date=&pmatsemit=%s
返回为json，edu_subject_id为对应id，undo为未写作业数量

**Comment by awesomehhhhh** [comment]
另：已批改中作业看分中 recordset 不应取[0]，而应做一个for i in recordset:

**Comment by cjyx9** [comment]
已收到,thanks🌝

**Comment by cjyx9** [comment]
内个，未写作业的api我暂时不用这个，因为
二次调用接口(先取id,再取作业详情)会产生许多不必要的内存占用，不如这个整合在一起的api
看分取0,是因为我只想看第一个批改了的作业分数，当然用循环输出全部也没有错
🌚🌚

**Comment by awesomehhhhh** [comment]
哦（我以为你是想要“ALL”->全部），而且因为我们学科比较多所以我采用的是先看数量再for，尽管我班有些人的没写作业有 76 个🤔
