### ISSUE TITLE
我又双挑毛病来了（

### ISSUE THREAD

**Issue by awesomehhhhh** [cjyx9/FakeAnoah#2]
1.还获取全部作业中 status应为-1而status为1是已完成作业，status为0是未完成作业 [status 为-1](http://api2.anoah.com/jwt/homework/publish/getListForStudent?user_id=1585745&status=-1&subject_id=1&class_id=73008&from_date=&to_date=&page=1&per_page=-1) [status为 1](http://api2.anoah.com/jwt/homework/publish/getListForStudent?user_id=1585745&status=1&subject_id=1&class_id=73008&from_date=&to_date=&page=1&per_page=-1) 
2.作业中的comment应该是[comment][text]是内容 具体也可见：[例子](http://api2.anoah.com/jwt/homework/publish/getListForStudent?user_id=1585733&status=-1&subject_id=7&class_id=73008&from_date=&to_date=&page=1&per_page=-1) 
另：你们班积分第一的人名，是不是打错了？曲奇饼（雾）？

**Comment by cjyx9** [comment]
哦🙄，我晚上回来看看吧

**Comment by awesomehhhhh** [comment]
（另：初中就有选修了吗，羡慕羡慕（？？？

**Comment by cjyx9** [comment]
一个星期有一节😂,这学期因为疫情取消了

**Comment by cjyx9** [comment]
改了,谢谢啊👀
